<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.bioimageanalysis.icy</groupId>
		<artifactId>pom-icy</artifactId>
		<version>2.1.1</version>
	</parent>

	<artifactId>icytomine</artifactId>
	<version>1.0.5</version>
	<name>Cytomine client for Icy</name>
	<description>Icytomine is a set of plugin that allows _Cytomine_ users to interact with their account directly from _ICY_.</description>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-shade-plugin</artifactId>
				<version>3.2.4</version>
				<executions>
					<execution>
						<phase>package</phase>
						<goals>
							<goal>shade</goal>
						</goals>
						<configuration>
							<artifactSet>
								<includes>
									<include>be.cytomine.client:cytomine-java-client</include>
									<include>com.googlecode.json-simple:json-simple</include>
									<include>javax.json:javax.json-api</include>
									<include>javax.json.bind:javax.json.bind-api</include>
									<include>org.glassfish:javax.json</include>
									<include>org.eclipse:yasson</include>
									<include>com.vividsolutions:jts-core</include>
									<include>org.geotools:gt-main</include>
									<include>org.japura:japura-gui</include>
									<include>org.apache.logging.log4j:log4j-api</include>
								</includes>
							</artifactSet>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>

	<dependencies>
		<dependency>
			<groupId>org.bioimageanalysis.icy</groupId>
			<artifactId>icy-kernel</artifactId>
			<version>2.4.2</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.bioimageanalysis.icy</groupId>
			<artifactId>icy-bioformats</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.bioimageanalysis.icy</groupId>
			<artifactId>icy-insubstantial</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.bioimageanalysis.icy</groupId>
			<artifactId>ezplug</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.bioimageanalysis.icy</groupId>
			<artifactId>protocols</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.bioimageanalysis.icy</groupId>
			<artifactId>blockvars</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.bioimageanalysis.icy</groupId>
			<artifactId>apache-httpclient</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.bioimageanalysis.icy</groupId>
			<artifactId>ehcache3</artifactId>
			<exclusions>
				<exclusion>
					<groupId>org.glassfish.jaxb</groupId>
					<artifactId>jaxb-runtime</artifactId>
				</exclusion>
			</exclusions>
			<scope>provided</scope>
		</dependency>

		<!-- cytomine java client -->
		<dependency>
			<groupId>be.cytomine.client</groupId>
			<artifactId>cytomine-java-client</artifactId>
			<version>2.3.0</version>
		</dependency>

		<!-- https://mvnrepository.com/artifact/com.googlecode.json-simple/json-simple/1.1.1 -->
		<dependency>
			<groupId>com.googlecode.json-simple</groupId>
			<artifactId>json-simple</artifactId>
			<version>1.1.1</version>
		</dependency>
		<!-- https://mvnrepository.com/artifact/javax.json/javax.json-api -->
		<dependency>
			<groupId>javax.json</groupId>
			<artifactId>javax.json-api</artifactId>
			<version>1.1.2</version>
		</dependency>
		<!-- https://mvnrepository.com/artifact/javax.json.bind/javax.json.bind-api -->
		<dependency>
			<groupId>javax.json.bind</groupId>
			<artifactId>javax.json.bind-api</artifactId>
			<version>1.0</version>
		</dependency>
		<!-- https://mvnrepository.com/artifact/org.glassfish/javax.json -->
		<dependency>
			<groupId>org.glassfish</groupId>
			<artifactId>javax.json</artifactId>
			<version>1.1.2</version>
		</dependency>
		<!-- https://mvnrepository.com/artifact/org.eclipse/yasson -->
		<dependency>
			<groupId>org.eclipse</groupId>
			<artifactId>yasson</artifactId>
			<version>1.0.1</version>
		</dependency>
		<!-- https://mvnrepository.com/artifact/javax.cache/cache-api -->
		<!-- <dependency> -->
		<!-- <groupId>javax.cache</groupId> -->
		<!-- <artifactId>cache-api</artifactId> -->
		<!-- <version>1.1.0</version> -->
		<!-- </dependency> -->
<!--
		<dependency>
			<groupId>org.apache.httpcomponents</groupId>
			<artifactId>fluent-hc</artifactId>
			<version>4.3.1</version>
		</dependency>
		<dependency>
			<groupId>org.apache.httpcomponents</groupId>
			<artifactId>httpclient</artifactId>
			<version>4.5.13</version>
		</dependency>
		<dependency>
			<groupId>org.apache.httpcomponents</groupId>
			<artifactId>httpclient-cache</artifactId>
			<version>4.5.13</version>
		</dependency>
		<dependency>
			<groupId>org.apache.httpcomponents</groupId>
			<artifactId>httpcore</artifactId>
			<version>4.4.14</version>
		</dependency>
		<dependency>
			<groupId>org.apache.httpcomponents</groupId>
			<artifactId>httpmime</artifactId>
			<version>4.5.13</version>
		</dependency>
-->
		<!-- https://mvnrepository.com/artifact/org.apache.logging.log4j/log4j-api -->
		<dependency>
			<groupId>org.apache.logging.log4j</groupId>
			<artifactId>log4j-api</artifactId>
			<version>2.18.0</version>
		</dependency>
		<!-- https://mvnrepository.com/artifact/com.vividsolutions/jts-core -->
		<dependency>
			<groupId>com.vividsolutions</groupId>
			<artifactId>jts-core</artifactId>
			<version>1.14.0</version>
		</dependency>
		<!-- https://mvnrepository.com/artifact/org.geotools/gt-main -->
		<dependency>
			<groupId>org.geotools</groupId>
			<artifactId>gt-main</artifactId>
			<version>18.2</version>
		</dependency>
		<!-- https://mvnrepository.com/artifact/org.japura/japura-gui -->
		<dependency>
			<groupId>org.japura</groupId>
			<artifactId>japura-gui</artifactId>
			<version>7.5.2</version>
		</dependency>
		<!-- https://mvnrepository.com/artifact/junit/junit -->
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.13.2</version>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<repositories>
		<repository>
			<id>icy</id>
			<url>https://icy-nexus.pasteur.fr/repository/Icy/</url>
		</repository>
		<repository>
			<id>jitpack.io</id>
			<url>https://jitpack.io</url>
		</repository>
		<repository>
			<id>osgeo</id>
			<url>https://repo.osgeo.org/repository/release/</url>
			<releases>
				<enabled>true</enabled>
			</releases>
		</repository>
	</repositories>

</project>